name: Deploy on merge

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest
    

  deploy:
    if: github.event.pull_request.merged == true
    needs: build-and-push
    uses: monacloud/workflows/.github/workflows/deploy-to-azure.yml@main
    with:
      tag: ${{ github.sha }}
    secrets:
      AZURE_KUBECONFIG: ${{ secrets.AZURE_KUBECONFIG }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
      CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }} 