name: Initial Deploy

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
        packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:initial
    

  deploy:
    needs: build-and-push
    uses: monacloud/workflows/.github/workflows/deploy-to-azure.yml@main
    with:
        tag: 'initial'
    secrets:
        AZURE_KUBECONFIG: ${{ secrets.AZURE_KUBECONFIG }}
        CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }} 